language: node_js
node_js:
  - 14
  - node

script: echo "Running tests against $(node -v)..."

jobs:
  allow_failures:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && coveralls < coverage/lcov.info